security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    encoders:
        CBA\UserBundle\Entity\User: sha512

    providers:
        database_users:
             id: fos_user.user_provider.username_email

    # http://symfony.com/doc/current/book/security.html#firewalls-authentication
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
   
        secured_area:
            pattern: ^/
            provider: database_users
            anonymous: true
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key: %secret%

    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        - { path: ^/admin, roles: ROLE_ADMIN }
